name: Weather Automation

on:
  schedule:
    - cron: '59 21 * * *'
  workflow_dispatch:

jobs:
  weather:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar requests
        run: pip install requests

      - name: Ejecutar programa
        run: python temps.py

      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Subir JSON
        run: |
          git add *.json
          git commit -m "Nuevo JSON automatico" || echo "Sin cambios"
          git push